# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3d57b04927a255c0495db447453a2e240580c39e45d984eba9f6263e722eb6cab6e0b0f6dd13165ce0b6a6e2c384f79025bd8ad804e28f345f540765b650174

test:
  secret_key_base: 4d862098dd3fab444a67df8475f099a13f79df571d8e3fdb5edf228923fc15708cea77cacad6c9f98526c18c050681adb3a369bbc12cb0bbb006da3851d143be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
