# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e87b4609240513db27aa8dffa52e6cb7b009f6e5df1c3969413b5905bfe8f9604f563b7c45c025b8aec2112481b9c0947540936967c8d08b7fba2757ced5db71

test:
  secret_key_base: 612ff5f1c728e283a83b8ae98303d5503462671efb315adb7a9e2f96b6eba965161d8779b080d617120ac724881cb3d3bfc90069ed476e0055e41e32121b6d47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
