# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec28ca5ad63fdc82c7739991936265e784252216f8031eae87103f8b8cd2f65f4090390c191c555eaab21d9679145d793dbb85c3f70b8a0045ec5cc17a912f63

test:
  secret_key_base: d9a6b919788238da7519a378b157ca0d840531105d4521e30d0e7ae40a0684fa7fbaece06c67750a3f639e4b42afbb5cd7052c21240c0929fb540fe95cd9e808

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
